apiVersion: apps/v1
kind: Deployment
metadata:
  name: dns-cache-deployment
spec:
  selector:
    matchLabels:
      app: dns-cache
  replicas: 1
  template:
    metadata:
      labels:
        app: dns-cache
    spec:
      containers:
        - name: dns-cache
          image: r.addops.soft.360.cn/dns-cache-ms/nginx-php:7.3
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "200Mi"
              cpu: "1"
            requests:
              memory: "100Mi"
              cpu: "1"
          args:
            - -cpus
            - "2"
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /home/q/system/dns_cache_ms
              name: dns-cache-ms
            - mountPath: /usr/local/nginx/conf/nginx.conf
              subPath: nginx.conf
              name: nginx-config
      volumes:
        - hostPath:
            path: /Users/oom/dev/www/dns/dns_cache_ms
          name: dns-cache-ms
        - name: nginx-config
          configMap:
            name: confnginx

---
apiVersion: v1
kind: Service
metadata:
  name: dns-cache-service
spec:
  selector:
    app: dns-cache
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
