version: '3'
services:
  mydb:
    image: postgres
    # volumes:
      # - ./pdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: sonar
      POSTGRES_DB: sonar
      POSTGRES_PASSWORD: sonar
    ports:
      - "5433:5432"
  sonarqube:
    image: sonarqube
    environment:
      sonar.jdbc.username: sonar
      sonar.jdbc.password: sonar
      sonar.jdbc.url: jdbc:postgresql://mydb:5432/sonar
    ports:
      - "9823:9000"
    volumes:
      - .sonar:/home/sonarqube/.sonar
      - ./scaner:/opt/sonarqube/scanner
  runner:
    container_name: 'gitlab_runner'
    build: ./server/gitlab-runner/
    ports:
      - '8093:8093'
    # volumes:
    #   - '$GITLAB_HOME/gitlab-runner/config:/etc/gitlab-runner'
    #   - '/var/run/docker.sock:/var/run/docker.sock'
  gitlab:
    image: 'gitlab/gitlab-ee:latest'
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.example.com:8929'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
    ports:
      - '8929:8929'
      - '2224:22'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'