version: "3.1"
services:
  hbase:
    build: ./server/hbase
    container_name: hbase
    ports:
      - "16010:16010"
    volumes:
      - ./logs:/opt/logs
      - ./www:/opt/htdocs

  spark-master:
    build: ./server/spark
    container_name: spark-master
    ports:
      - "6066:6066"
      - "7077:7077"
      - "8180:8080"
      - "8188:8088"
      - "4040:4040"
      - "18180:18080"
    links:
      - "hbase"
    environment:
      RPWD: 123456
    command: "/usr/local/spark/bin/spark-class org.apache.spark.deploy.master.Master "
    volumes:
      - ./www:/opt/htdocs
      - ./logs:/opt/logs
      - ./data:/data

  spark-cluster:
    build: ./server/spark
    container_name: spark-cluster
    ports:
      - "8181:8081"
    links:
      - "hbase"
      - "spark-master"
    command: "./bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077"
    volumes:
      - ./www:/opt/htdocs
      - ./logs:/opt/logs
      - ./data:/data
  jobmanager:
    image: ${FLINK_DOCKER_IMAGE_NAME:-flink}
    expose:
      - "6123"
    ports:
      - "8081:8081"
    command: jobmanager
    volumes:
      - ./www:/opt/htdocs
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager

  taskmanager:
    image: ${FLINK_DOCKER_IMAGE_NAME:-flink}
    expose:
      - "6121"
      - "6122"
    depends_on:
      - jobmanager
    command: taskmanager
    links:
      - "jobmanager:jobmanager"
    volumes:
      - ./www:/opt/htdocs
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
  jiagu-mini:
    container_name: centos7
    image: oomcc/centos7:latest
    privileged: true
    volumes:
      - ./www:/opt/htdocs
      - ./data:/data
      - ./www/source:/root/source
    ports:
      - 81:80
      - 443:443
      - 21:21
      - 9527:9527
  ocr2:
    image: oomcc/ocr:latest
    container_name: ocr2
    working_dir: /data/chineseocr_lite
    volumes:
      - "./spider:/data"
    ports:
      - "7777:8080"
    entrypoint: /bin/bash -c "python app.py 8080"
    stdin_open: true
    tty: true
