FROM nginx

ADD resources/etc/ /etc/
ADD resources/sources.list /etc/apt/sources.list

RUN cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
	&& echo "Asia/Shanghai" > /etc/timezone 
COPY resources/headers-more-nginx-module-0.33.tar.gz /tmp/htdocs/headers-more-nginx-module-0.33.tar.gz
COPY resources/nginx-1.15.12.tar.gz /tmp/htdocs/nginx-1.15.12.tar.gz

RUN mkdir -p /tmp/htdocs/headers-more-nginx-module \
        && tar -xf /tmp/htdocs/headers-more-nginx-module-0.33.tar.gz -C /tmp/htdocs/headers-more-nginx-module --strip-components=1 \
        && rm /tmp/htdocs/headers-more-nginx-module-0.33.tar.gz

RUN mkdir -p /tmp/htdocs/nginx-1.15.12 \
        && tar -xf /tmp/htdocs/nginx-1.15.12.tar.gz -C /tmp/htdocs/nginx-1.15.12 --strip-components=1 \
        && rm /tmp/htdocs/nginx-1.15.12.tar.gz

#RUN mkdir /opt/htdocs && mkdir -p /data/logs/nginx && mkdir /data/logs/server_doing
#RUN chown -R www-data.www-data /opt/htdocs /data/logs


#RUN cd /tmp/htdocs/nginx-1.15.12  && ./configure \
# --prefix=/etc/nginx \
# --sbin-path=/usr/sbin/nginx \
# --modules-path=/usr/lib/nginx/modules \
# --conf-path=/etc/nginx/nginx.conf \
# --error-log-path=/var/log/nginx/error.log \
# --http-log-path=/var/log/nginx/access.log \
# --pid-path=/var/run/nginx.pid \
# --lock-path=/var/run/nginx.lock \
# --http-client-body-temp-path=/var/cache/nginx/client_temp \
# --http-proxy-temp-path=/var/cache/nginx/proxy_temp \
# --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp \
# --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp \
# --http-scgi-temp-path=/var/cache/nginx/scgi_temp \
# --user=nginx \
# --group=nginx \
# --with-compat \
# --with-file-aio \
# --with-threads \
# --with-http_addition_module \
# --with-http_auth_request_module \
# --with-http_dav_module \
# --with-http_flv_module \
# --with-http_gunzip_module \
# --with-http_gzip_static_module \
# --with-http_mp4_module \
# --with-http_random_index_module \
# --with-http_realip_module \
# --with-http_secure_link_module \
# --with-http_slice_module \
# --with-http_ssl_module \
# --with-http_stub_status_module \
# --with-http_sub_module \
# --with-http_v2_module \
# --with-mail \
# --with-mail_ssl_module \
# --with-stream \
# --with-stream_realip_module \
# --with-stream_ssl_module \
# --with-stream_ssl_preread_module \
# --with-cc-opt='-g -O2 -fdebug-prefix-map=/data/builder/debuild/nginx-1.15.12/debian/debuild-base/nginx-1.15.12=. -fstack-protector-strong -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fPIC' \
# --with-ld-opt='-Wl,-z,relro -Wl,-z,now -Wl,--as-needed -pie' \
# --add-module=/tmp/htdocs/headers-more-nginx-module
#RUN cp /usr/sbin/nginx /usr/sbin/nginx.bak
#RUN cp /opt/nginx /usr/sbin/

EXPOSE 80
VOLUME [ "/opt", "/data/logs" ]
