#!/bin/bash
supervisord -c /etc/supervisord.conf
source /etc/profile
supervisorctl reread
supervisorctl update
supervisorctl start all
/opt/remi/php73/root/usr/sbin/php-fpm -R
/usr/local/nginx/sbin/nginx -c /usr/local/nginx/conf/nginx.conf -g "daemon off;"
/bin/bash
